## Matrices

In [6]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

A

array([[  56. ,    0. ,    4.4,   68. ],
       [   1.2,  104. ,   52. ,    8. ],
       [   1.8,  135. ,   99. ,    0.9]])

In [7]:
calories = A.sum(axis=0)  # Sum vertically
calories

array([  59. ,  239. ,  155.4,   76.9])

In [8]:
percentage = (100 * A)/calories.reshape(1, 4)  # Divide 3x4 matrix by 1x4 matrix
percentage

array([[ 94.91525424,   0.        ,   2.83140283,  88.42652796],
       [  2.03389831,  43.51464435,  33.46203346,  10.40312094],
       [  3.05084746,  56.48535565,  63.70656371,   1.17035111]])

## Broadcasting

In [13]:
m1 = np.array([1, 2, 3, 4])
m1 = m1 + 100
m1

array([101, 102, 103, 104])

In [17]:
m2 = np.array([[1, 0, 0],
               [2, 0, 0],
               [3, 0, 0]])
m2 = m2 + 100
m2

array([[101, 100, 100],
       [102, 100, 100],
       [103, 100, 100]])

In [18]:
m3 = np.array([[10],
               [11],
               [12]])

m2 = m2 + m3
m2

array([[111, 110, 110],
       [113, 111, 111],
       [115, 112, 112]])

In [19]:
m4 = np.array([25, 26, 27])
m2 = m2 + m4
m2

array([[136, 136, 137],
       [138, 137, 138],
       [140, 138, 139]])

## Vectors

In [53]:
v1 = np.random.randn(5)  # Creates a rank 1 array
v1

array([-0.61966125,  0.88606993, -0.59599406,  0.14722126,  0.1576896 ])

In [54]:
v1.shape

(5,)

In [26]:
v1.T  # Transpose

array([ 1.14768051, -0.70621693,  1.00094445,  0.1808542 ,  0.81008868])

In [29]:
res = np.dot(v1, v1.T)  # We expect an array since we are multiplying 5x1 matrix with 1x5 matrix
res # But actual result is:

3.5067546112723131

This is due to the fact that np.random.randn(5) created a rank 1 array instead of a vector.

To get our desired [column] vector, we need to do the following:

In [36]:
v2 = np.random.randn(5, 1)  # Define matrix dimension explicitly in the argument
v2

array([[-0.73401304],
       [-0.29456306],
       [-0.94697596],
       [-1.62819555],
       [ 2.04608883]])

In [37]:
v2.shape

(5, 1)

Now, if we take the transpose, we get a 1x5 matrix (i.e. a row vector):

In [38]:
v2.T

array([[-0.73401304, -0.29456306, -0.94697596, -1.62819555,  2.04608883]])

And on multiplying the 5x1 vector with it's transpose results in a 5x5 matrix:

In [39]:
res = np.dot(v2, v2.T)
res

array([[ 0.53877515,  0.21621313,  0.69509271,  1.19511677, -1.50185589],
       [ 0.21621313,  0.0867674 ,  0.27894414,  0.47960627, -0.60270219],
       [ 0.69509271,  0.27894414,  0.89676347,  1.54186205, -1.93759693],
       [ 1.19511677,  0.47960627,  1.54186205,  2.65102076, -3.33143273],
       [-1.50185589, -0.60270219, -1.93759693, -3.33143273,  4.18647948]])

When unsure about the dimensions of a matrix, make sure you throw in an assert statement to check if we have a matrix of expected dimensions: 

In [44]:
assert(res.shape == (5, 5))

If for some reason, we end up with a rank 1 array, we can 'reshape' it into a vector so that we have consistent results when performing vector operations:

In [55]:
print(v1)
print(v1.shape)

v1 = v1.reshape((5, 1))

print(v1)
print(v1.shape)

[-0.61966125  0.88606993 -0.59599406  0.14722126  0.1576896 ]
(5,)
[[-0.61966125]
 [ 0.88606993]
 [-0.59599406]
 [ 0.14722126]
 [ 0.1576896 ]]
(5, 1)
